const customStyles = {
  container: (provided, { isFocused }) => ({
    ...provided,
    border: '1px solid #A0A0A0',
    borderColor: isFocused ? '#FEC92D' : '#A0A0A0',
    borderRadius: '8px',
    margin: '16px 0',
    transition: '.3s',
  }),
  option: (provided, { isFocused }) => ({
    ...provided,
    background: isFocused ? 'transparent' : '#2A2E32',
    border: 'none',
    color: isFocused ? '#FEC92D' : '#A0A0A0',
    cursor: 'pointer',
    fontWeight: isFocused ? 400 : 300,
    letterSpacing: isFocused ? '1px' : '0',
    paddingLeft: isFocused ? '16px' : '8px',
    transition: '.3s padding-left, .3s letter-spacing',
    '&:active': {
      backgroundColor: 'transparent',
    },
    '&:hover': {
      fontWeight: '400',
      letterSpacing: '1px',
      paddingLeft: '16px',
    },
  }),
  valueContainer: provided => ({
    ...provided,
    background: '#2A2E32',
    border: '2px solid transparent',
    borderRadius: '8px',
    cursor: 'pointer',
    minHeight: '52px',
  }),
  control: provided => ({
    ...provided,
    backgroundColor: 'transparent',
    border: 'none',
    boxShadow: 'none',
    cursor: 'pointer',
    minWidth: 300,
  }),
  menu: provided => ({
    ...provided,
    backgroundColor: '#2a2e32',
    border: '1px solid #A0A0A0',
    borderRadius: '8px',
    left: '-1px',
    position: 'absolute',
  }),
  multiValue: provided => ({
    ...provided,
    background: 'transparent',
    borderRadius: '27px',
    color: '#a0a0a0',
    border: '1px solid #A0A0A0',
    display: 'flex',
    justifyContent: 'space-between',
    padding: '4px 14px',
  }),
  multiValueLabel: provided => ({
    ...provided,
    color: '#a0a0a0',
    textTransform: 'uppercase',
  }),
  multiValueRemove: provided => ({
    ...provided,
    background: 'transparent',
    transition: '.3s',
    '&:hover': {
      backgroundColor: 'transparent',
      color: '#e62a2a',
      transform: 'scale(1.3)',
    },
  }),
  clearIndicator: provided => ({
    ...provided,
    background: 'transparent',
    color: '#8a8a8a',
    transition: '.3s',
    '&:hover': {
      backgroundColor: 'transparent',
      color: '#e62a2a',
      transform: 'scale(1.3)',
    },
  }),
  indicatorscontainer: provided => ({
    ...provided,
    background: 'transparent',
  }),
  placeholder: provided => ({
    ...provided,
    color: '#A0A0A0',
    fontFamily: 'Poppins',
    fontSize: '16px',
    fontWeight: 300,
    letterSpacing: '0.48px',
  }),
  indicatorSeparator: provided => ({
    ...provided,
    display: 'none',
  }),
  input: () => ({
    color: '#A0A0A0',
  }),
  dropdownIndicator: provided => ({
    ...provided,
    color: '#8a8a8a',
    transition: '.3s',
    '&:hover': {
      backgroundColor: 'transparent',
      color: '#FFF',
      transform: 'scale(1.3)',
    },
  }),
}

export default customStyles
